# Generated by Django 3.2.5 on 2022-01-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0005_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('budget', models.FloatField()),
                ('org_language', models.CharField(max_length=200)),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('genres', models.ManyToManyField(blank=True, related_name='genres', to='MovieRecommender.Genre')),
                ('production_companies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MovieRecommender.company')),
            ],
        ),
    ]
