# Generated by Django 3.2.5 on 2022-01-08 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0006_movie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('genre_id', 'name')},
        ),
    ]
