# Generated by Django 3.2.5 on 2022-01-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0007_alter_genre_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company_id', 'name')},
        ),
    ]
