# Generated by Django 3.2.5 on 2022-01-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0012_auto_20220109_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-movie_id']},
        ),
    ]
