# Generated by Django 3.2.5 on 2022-01-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('MovieRecommender', '0014_alter_movie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(default='', max_length=200)),
                ('picture_path', models.CharField(max_length=200)),
                ('birth_date', models.DateField(default=None)),
                ('sex', models.CharField(default='', max_length=200)),
                ('fav_movies', models.ManyToManyField(blank=True, related_name='fav_movies', to='MovieRecommender.Movie')),
            ],
        ),
    ]
