# Generated by Django 3.2.5 on 2022-01-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0018_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
