# Generated by Django 3.2.5 on 2022-01-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0020_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='character',
            field=models.CharField(default='', max_length=200),
        ),
    ]
