# Generated by Django 3.2.5 on 2022-01-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0022_actor_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_id',
            field=models.IntegerField(default=0.0),
        ),
    ]
