# Generated by Django 3.2.5 on 2022-01-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0023_actor_actor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='adults',
            field=models.CharField(default='False', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default='https://www.scifi-movies.com/images/site/en/affiche_nondisponible.jpg', max_length=200),
        ),
    ]
