# Generated by Django 3.2.5 on 2022-01-16 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0024_auto_20220116_1218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together=set(),
        ),
    ]
