# Generated by Django 3.2.5 on 2022-01-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0025_alter_genre_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
    ]
