# Generated by Django 3.2.5 on 2022-01-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0026_remove_movie_production_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture_path',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/1/1e/Default-avatar.jpg', max_length=200),
        ),
    ]
