# Generated by Django 3.2.5 on 2022-01-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0028_alter_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
